# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Lift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PSOLib', '~> 1.0.0'
  pod 'Buckets', '~> 2.0'
  # Pods for Lift

end
